#!/bin/sh
# Copyright (C) 2024 Tom <fjrcn@outlook.com>
manual=$(uci -q get xmodem.main.block_auto_probe)
[ "${manual}" -eq 1 ] && exit
logger -t modem_hotplug "usb_event slot: ${DEVPATH} action: ${ACTION}"
hotplug_add_delay=$(uci -q get xmodem.main.hotplug_add_delay || echo 8)
[ -z "${DEVNUM}" ] && exit


slot=$(basename "${DEVPATH}")
logger -t modem_hotplug "usb_event run slot: ${slot} action: ${ACTION}"
case "${ACTION}" in
    bind|\
    add)
        (/usr/share/xmodem/modem_scan.sh add "${slot}" usb "${hotplug_add_delay}" >/dev/null 2>&1) &
        ;;
    remove)
        ( /usr/share/xmodem/modem_scan.sh disable "${slot}" >/dev/null 2>&1 ) &
        ;;
esac
